# Generated by Django 4.2.7 on 2026-01-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='scope',
            field=models.CharField(blank=True, help_text='Scope of work assigned (e.g., CMU, BRICK, etc.)', max_length=50, null=True),
        ),
    ]
