# Generated by Django 4.2.7 on 2026-01-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PUBLIC_VIEW', 'Public View'), ('FOREMAN', 'Foreman'), ('SUPERINTENDENT', 'Superintendent / Site Supervisor'), ('PROJECT_MANAGER', 'Project Manager'), ('HR', 'HR'), ('FINANCE', 'Finance'), ('AUDITOR', 'Auditor'), ('ADMIN', 'Admin'), ('SYSTEM_ADMIN', 'System Admin'), ('SUPERADMIN', 'Superadmin'), ('ROOT_SUPERADMIN', 'Root Superadmin'), ('GENERAL_CONTRACTOR', 'General Contractor')], default='WORKER', max_length=50),
        ),
    ]
