# Generated by Django 4.2.7 on 2026-01-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_roles_and_divisions'),
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
    ]
