# Generated by Django 4.2.7 on 2026-01-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_spectrum_division_code_alter_branch_code'),
        ('accounts', '0010_merge_20260113_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Division/Branch assignment (required for Branch Managers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_managers', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ROOT_SUPERADMIN', 'Root Superadmin'), ('ADMIN', 'Admin'), ('BRANCH_MANAGER', 'Branch Manager'), ('PROJECT_MANAGER', 'Project Manager')], default='PROJECT_MANAGER', max_length=50),
        ),
    ]
