# Generated by Django 4.2.7 on 2026-01-04 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('saturdays', models.BooleanField(default=False, help_text='Include Saturdays as workdays')),
                ('full_weekends', models.BooleanField(default=False, help_text='Include full weekends as workdays')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Visible on public portal')),
                ('public_pin', models.CharField(blank=True, help_text='Optional PIN for public access', max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('general_contractor', models.ForeignKey(blank=True, limit_choices_to={'role': 'GENERAL_CONTRACTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gc_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'PROJECT_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_projects', to=settings.AUTH_USER_MODEL)),
                ('superintendent', models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPERINTENDENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Tuesday of the week')),
                ('handoff_from_estimator', models.BooleanField(default=False)),
                ('handoff_to_foreman', models.BooleanField(default=False)),
                ('site_specific_safety_plan', models.BooleanField(default=False)),
                ('weekly_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_super', models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPERINTENDENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_approved_checklists', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by_pm', models.ForeignKey(blank=True, limit_choices_to={'role': 'PROJECT_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_confirmed_checklists', to=settings.AUTH_USER_MODEL)),
                ('drafted_by', models.ForeignKey(limit_choices_to={'role__in': ['FOREMAN', 'SUPERINTENDENT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_checklists', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_checklists', to='projects.project')),
            ],
            options={
                'verbose_name': 'Weekly Checklist',
                'verbose_name_plural': 'Weekly Checklists',
                'ordering': ['-week_start_date'],
                'unique_together': {('project', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='ProjectScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('CMU', 'CMU'), ('BRICK', 'BRICK'), ('CAST_STONE', 'CAST STONE'), ('MSV', 'MSV'), ('STUCCO', 'STUCCO'), ('EIFS', 'EIFS'), ('THIN_BRICK', 'THIN BRICK'), ('FBD_STONE', 'FBD STONE')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('installed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='Sq.Ft', help_text='Unit of measurement', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Scope',
                'verbose_name_plural': 'Project Scopes',
                'unique_together': {('project', 'scope_type')},
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('masons_count', models.IntegerField(default=0)),
                ('tenders_count', models.IntegerField(default=0)),
                ('operators_count', models.IntegerField(default=0)),
                ('installed_quantities', models.JSONField(default=dict, help_text='Dict of scope_type: quantity installed')),
                ('notes', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(default=list, help_text='List of photo URLs/paths')),
                ('blockers', models.JSONField(default=list, help_text='List of structured delay reasons')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPERINTENDENT', 'PROJECT_MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_daily_reports', to=settings.AUTH_USER_MODEL)),
                ('foreman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.project')),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
