# Generated by Django 4.2.7 on 2026-01-04 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='foreman',
            field=models.ForeignKey(blank=True, help_text='Optional foreman assignment', limit_choices_to={'role': 'FOREMAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreman_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='qty_sq',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity per square foot', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for this scope', null=True),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for this scope', null=True),
        ),
    ]
