# Generated by Django 4.2.7 on 2026-01-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_foreman_project_qty_sq_projectscope_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, help_text='Client name for this project', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='work_location',
            field=models.CharField(blank=True, help_text='Location where work is performed', max_length=500, null=True),
        ),
    ]
