# Generated by Django 4.2.7 on 2026-01-07 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_client_name_project_work_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(help_text='Phase/Scope (e.g., 4210 - CMU- Labor)', max_length=100)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity completed', max_digits=12, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Labor Entry',
                'verbose_name_plural': 'Labor Entries',
                'ordering': ['employee__employee_number'],
            },
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When report was completed', null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='delays_by_others',
            field=models.TextField(blank=True, help_text='Delays by others description', null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='jha_review',
            field=models.BooleanField(default=False, help_text='JHA Review For Work Performed'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='location',
            field=models.CharField(blank=True, help_text='Work location', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='phase',
            field=models.CharField(blank=True, help_text='Phase/Scope (e.g., 4210 - CMU- Labor)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='report_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated report number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='safety_meeting_held',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='scaffolding_inspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='temperature_am',
            field=models.IntegerField(blank=True, help_text='Temperature in AM', null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='temperature_pm',
            field=models.IntegerField(blank=True, help_text='Temperature in PM', null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_cloudy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_notes',
            field=models.TextField(blank=True, help_text='Additional weather notes', null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_rain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_snow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_sunny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_wind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='work_performed',
            field=models.TextField(blank=True, help_text='Description of work performed', null=True),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['report_number'], name='projects_da_report__cc2890_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['project', 'date'], name='projects_da_project_eb4f03_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['status'], name='projects_da_status_5f5fe6_idx'),
        ),
        migrations.AddField(
            model_name='laborentry',
            name='daily_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='projects.dailyreport'),
        ),
        migrations.AddField(
            model_name='laborentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
