# Generated by Django 4.2.7 on 2026-01-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_laborentry_dailyreport_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
    ]
