# Generated by Django 4.2.7 on 2026-01-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_spectrum_division_code_alter_branch_code'),
        ('projects', '0005_remove_daily_report_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='spectrum_division_code',
            field=models.CharField(blank=True, db_index=True, help_text="Division code from Spectrum (e.g., '111', '121') - used to match jobs to divisions", max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(help_text='Division/Branch (branches are divisions)', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='branches.branch'),
        ),
    ]
