# Generated by Django 4.2.7 on 2026-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_spectrum_division_code_alter_project_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
    ]
