# Generated by Django 4.2.7 on 2026-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_inactive_and_closed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='spectrum_project_manager',
            field=models.CharField(blank=True, help_text='Project Manager name from Spectrum (fallback if User not matched)', max_length=100, null=True),
        ),
    ]
