# Generated by Django 4.2.7 on 2026-01-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_spectrum_project_manager_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='spectrum_complete_date',
            field=models.DateField(blank=True, help_text='Actual Complete Date from Spectrum', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spectrum_cost_types',
            field=models.TextField(blank=True, help_text='Comma-separated list of cost types from Spectrum phases', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spectrum_create_date',
            field=models.DateField(blank=True, help_text='Job Created Date from Spectrum', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spectrum_est_complete_date',
            field=models.DateField(blank=True, help_text='Estimated Complete Date from Spectrum', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spectrum_est_start_date',
            field=models.DateField(blank=True, help_text='Estimated Start Date from Spectrum', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spectrum_original_contract',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original Contract Amount from Spectrum', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spectrum_projected_complete_date',
            field=models.DateField(blank=True, help_text='Projected Complete Date from Spectrum', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spectrum_start_date',
            field=models.DateField(blank=True, help_text='Actual Start Date from Spectrum', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spectrum_total_estimated_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Estimated Dollars from all phases', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spectrum_total_jtd_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Job To Date Dollars from all phases', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spectrum_total_projected_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Projected Dollars from all phases', max_digits=14, null=True),
        ),
    ]
