# Generated by Django 5.2.10 on 2026-01-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_add_spectrum_dates_amounts_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foreman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Foreman name', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this foreman is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foreman',
                'verbose_name_plural': 'Foremen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScopeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Scope code (e.g., CMU, BRICK)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name (e.g., CMU, BRICK, CAST STONE)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scope type is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scope Type',
                'verbose_name_plural': 'Scope Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='projectscope',
            options={'ordering': ['scope_type__name'], 'verbose_name': 'Project Scope', 'verbose_name_plural': 'Project Scopes'},
        ),
        migrations.RemoveField(
            model_name='projectscope',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projectscope',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='projectscope',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='projectscope',
            name='unit',
        ),
        migrations.AddField(
            model_name='projectscope',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Duration in days (when set, can change estimation_end_date)', null=True),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='estimation_end_date',
            field=models.DateField(blank=True, help_text='Estimated end date for this scope', null=True),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='estimation_start_date',
            field=models.DateField(blank=True, help_text='Estimated start date for this scope', null=True),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='full_weekends',
            field=models.BooleanField(default=False, help_text='Include full weekends as workdays'),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='masons',
            field=models.IntegerField(default=0, help_text='Number of masons'),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='operators',
            field=models.IntegerField(default=0, help_text='Number of operators'),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='qty_sq_ft',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity per square foot', max_digits=12),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='saturdays',
            field=models.BooleanField(default=False, help_text='Include Saturdays as workdays'),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='tenders',
            field=models.IntegerField(default=0, help_text='Number of tenders'),
        ),
        migrations.AlterField(
            model_name='projectscope',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this scope', null=True),
        ),
        migrations.AlterField(
            model_name='projectscope',
            name='installed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Installed quantity (updated during meetings)', max_digits=12),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='foreman',
            field=models.ForeignKey(blank=True, help_text='Foreman/screw assigned to this scope', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_scopes', to='projects.foreman'),
        ),
        migrations.AlterField(
            model_name='projectscope',
            name='scope_type',
            field=models.ForeignKey(help_text='Type of scope (CMU, BRICK, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='project_scopes', to='projects.scopetype'),
        ),
    ]
