# Generated by Django 4.2.7 on 2026-01-04 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type', models.CharField(help_text='Equipment type/category', max_length=100)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('cycle_length', models.IntegerField(default=28, help_text='Billing cycle length in days')),
                ('status', models.CharField(choices=[('IN_YARD', 'In Yard'), ('ON_SITE', 'On Site'), ('IN_TRANSIT', 'In Transit'), ('MAINTENANCE', 'Maintenance')], default='IN_YARD', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['asset_number'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_out_date', models.DateTimeField()),
                ('transfer_out_notes', models.TextField(blank=True, null=True)),
                ('condition_notes', models.TextField(blank=True, help_text='Equipment condition at transfer', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('receipt_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='equipment.equipment')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='branches.branch')),
                ('from_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='projects.project')),
                ('receiving_foreman', models.ForeignKey(limit_choices_to={'role': 'FOREMAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
                ('sending_foreman', models.ForeignKey(limit_choices_to={'role': 'FOREMAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='branches.branch')),
                ('to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='projects.project')),
            ],
            options={
                'verbose_name': 'Equipment Transfer',
                'verbose_name_plural': 'Equipment Transfers',
                'ordering': ['-transfer_out_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='branches.branch')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='equipment.equipment')),
                ('foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Equipment Assignment',
                'verbose_name_plural': 'Equipment Assignments',
                'ordering': ['-assigned_on'],
            },
        ),
    ]
