# Generated by Django 4.2.7 on 2026-01-21 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0004_branch_portal_password'),
        ('projects', '0006_project_spectrum_division_code_alter_project_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(help_text='Date of the meeting')),
                ('notes', models.TextField(blank=True, help_text='General meeting notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch/Division for this meeting (optional, for branch-specific meetings)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='branches.branch')),
                ('created_by', models.ForeignKey(help_text='User who created the meeting', on_delete=django.db.models.deletion.PROTECT, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masons', models.IntegerField(default=0, help_text='Number of masons on this job')),
                ('labors', models.IntegerField(default=0, help_text='Number of labors on this job')),
                ('notes', models.TextField(blank=True, help_text='Job-specific notes for this meeting', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(help_text='The meeting this job entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_jobs', to='meetings.meeting')),
                ('project', models.ForeignKey(help_text='The project/job being discussed', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_entries', to='projects.project')),
            ],
            options={
                'verbose_name': 'Meeting Job Entry',
                'verbose_name_plural': 'Meeting Job Entries',
                'ordering': ['-meeting__meeting_date', 'project__job_number'],
                'indexes': [models.Index(fields=['meeting', 'project'], name='meetings_me_meeting_df3443_idx'), models.Index(fields=['project'], name='meetings_me_project_a68bca_idx')],
                'unique_together': {('meeting', 'project')},
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_date'], name='meetings_me_meeting_5fb78c_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['branch'], name='meetings_me_branch__7636fb_idx'),
        ),
    ]
