# Generated by Django 4.2.7 on 2026-01-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingjob',
            name='handoff_from_estimator',
            field=models.BooleanField(default=False, help_text='Handoff from Estimator'),
        ),
        migrations.AddField(
            model_name='meetingjob',
            name='handoff_to_foreman',
            field=models.BooleanField(default=False, help_text='Handoff to Foreman'),
        ),
        migrations.AddField(
            model_name='meetingjob',
            name='site_specific_safety_plan',
            field=models.BooleanField(default=False, help_text='Site Specific Safety Plan'),
        ),
        migrations.AlterField(
            model_name='meetingjob',
            name='labors',
            field=models.IntegerField(default=0, help_text='Number of labors on this job (deprecated - use MeetingJobPhase)'),
        ),
        migrations.AlterField(
            model_name='meetingjob',
            name='masons',
            field=models.IntegerField(default=0, help_text='Number of masons on this job (deprecated - use MeetingJobPhase)'),
        ),
        migrations.CreateModel(
            name='MeetingJobPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_code', models.CharField(help_text='Phase code (e.g., from SpectrumPhaseEnhanced)', max_length=50)),
                ('phase_description', models.TextField(blank=True, help_text='Description of the phase', null=True)),
                ('masons', models.IntegerField(default=0, help_text='Number of masons for this phase')),
                ('operators', models.IntegerField(default=0, help_text='Number of operators for this phase')),
                ('labors', models.IntegerField(default=0, help_text='Number of labors for this phase')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Total quantity for this phase', max_digits=12)),
                ('installed_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Installed quantity for this phase', max_digits=12)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in days for this phase', null=True)),
                ('notes', models.TextField(blank=True, help_text='Phase-specific notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_job', models.ForeignKey(help_text='The meeting job entry this phase belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='meetings.meetingjob')),
            ],
            options={
                'verbose_name': 'Meeting Job Phase',
                'verbose_name_plural': 'Meeting Job Phases',
                'ordering': ['phase_code'],
                'indexes': [models.Index(fields=['meeting_job', 'phase_code'], name='meetings_me_meeting_7096aa_idx')],
                'unique_together': {('meeting_job', 'phase_code')},
            },
        ),
    ]
