# Generated by Django 5.2.10 on 2026-01-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='week_number',
            field=models.IntegerField(blank=True, help_text='Week number of the year (1-53) calculated from meeting_date', null=True),
        ),
    ]
