# Generated by Django 4.2.7 on 2026-01-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(help_text='Valid Spectrum Company', max_length=3)),
                ('job_number', models.CharField(help_text='Job File Maintenance', max_length=10)),
                ('job_description', models.CharField(blank=True, max_length=25, null=True)),
                ('division', models.CharField(blank=True, max_length=5, null=True)),
                ('address_1', models.CharField(blank=True, max_length=30, null=True)),
                ('address_2', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('project_manager', models.CharField(blank=True, max_length=15, null=True)),
                ('superintendent', models.CharField(blank=True, max_length=15, null=True)),
                ('estimator', models.CharField(blank=True, max_length=15, null=True)),
                ('certified_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status_code', models.CharField(blank=True, help_text='(A)ctive, (I)nactive or (C)omplete', max_length=1, null=True)),
                ('work_state_tax_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=15, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time this job was synced from Spectrum', null=True)),
            ],
            options={
                'verbose_name': 'Spectrum Job',
                'verbose_name_plural': 'Spectrum Jobs',
                'db_table': 'spectrum_job',
                'indexes': [models.Index(fields=['company_code', 'job_number'], name='spectrum_jo_company_0269ee_idx'), models.Index(fields=['status_code'], name='spectrum_jo_status__46af6c_idx'), models.Index(fields=['project_manager'], name='spectrum_jo_project_b0165c_idx'), models.Index(fields=['superintendent'], name='spectrum_jo_superin_f49026_idx')],
                'unique_together': {('company_code', 'job_number')},
            },
        ),
    ]
