# Generated by Django 4.2.7 on 2026-01-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrumjob',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='error_code',
            field=models.CharField(blank=True, help_text='Error Code if any', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='error_column',
            field=models.CharField(blank=True, help_text='Error Column if any', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='error_description',
            field=models.CharField(blank=True, help_text='Error Description if any', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='fax_phone',
            field=models.CharField(blank=True, help_text='Fax', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='field_1',
            field=models.CharField(blank=True, help_text='Placeholder for future fields', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='field_2',
            field=models.CharField(blank=True, help_text='Placeholder for future fields', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='field_3',
            field=models.CharField(blank=True, help_text='Placeholder for future fields', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='field_4',
            field=models.CharField(blank=True, help_text='Placeholder for future fields', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='field_5',
            field=models.CharField(blank=True, help_text='Placeholder for future fields', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='job_site_phone',
            field=models.CharField(blank=True, help_text='Site phone', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude (Numeric 11)', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='legal_desc',
            field=models.TextField(blank=True, help_text='Legal Description', max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude (Numeric 11)', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='original_contract',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original Contract (Numeric 14)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='phone',
            field=models.CharField(blank=True, help_text='Telephone', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='price_method_code',
            field=models.CharField(blank=True, help_text='(F)ixed Price; (T)ime & Material; (C)ost Plus or (U)nit Price', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='total_units',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Job units (Numeric 9)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='spectrumjob',
            name='wo_site',
            field=models.CharField(blank=True, help_text='Site', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='spectrumjob',
            name='contract_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
