# Generated by Django 4.2.7 on 2026-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum', '0002_spectrumjob_comment_spectrumjob_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumJobContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(help_text='Valid Spectrum Company', max_length=3)),
                ('job_number', models.CharField(help_text='Job File Maintenance', max_length=10)),
                ('job_description', models.CharField(blank=True, max_length=25, null=True)),
                ('status_code', models.CharField(blank=True, help_text='Job status', max_length=1, null=True)),
                ('project_manager', models.CharField(blank=True, max_length=15, null=True)),
                ('superintendent', models.CharField(blank=True, max_length=15, null=True)),
                ('estimator', models.CharField(blank=True, max_length=15, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_id', models.IntegerField(help_text='Contact Id (Number 10)')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('addr_1', models.CharField(blank=True, help_text='Contact Primary Address 1', max_length=30, null=True)),
                ('addr_2', models.CharField(blank=True, help_text='Contact Primary Address 2', max_length=30, null=True)),
                ('addr_city', models.CharField(blank=True, max_length=25, null=True)),
                ('addr_state', models.CharField(blank=True, max_length=2, null=True)),
                ('addr_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('addr_country', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact Primary Phone', max_length=14, null=True)),
                ('email1', models.CharField(blank=True, help_text='Contact Email 1', max_length=80, null=True)),
                ('email2', models.CharField(blank=True, help_text='Contact Email 2', max_length=80, null=True)),
                ('email3', models.CharField(blank=True, help_text='Contact Email 3', max_length=80, null=True)),
                ('remarks', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, help_text='Contact Status', max_length=1, null=True)),
                ('otype', models.CharField(blank=True, help_text='Organization Type: V(endor), C(ustomer), E(mployee) or O(ther)', max_length=1, null=True)),
                ('oname', models.CharField(blank=True, help_text='Organization Name', max_length=40, null=True)),
                ('ocity', models.CharField(blank=True, help_text='Organization City', max_length=25, null=True)),
                ('ostate', models.CharField(blank=True, help_text='Organization State', max_length=2, null=True)),
                ('ostatus', models.CharField(blank=True, help_text='Organization Status', max_length=1, null=True)),
                ('error_code', models.CharField(blank=True, max_length=1, null=True)),
                ('error_description', models.CharField(blank=True, max_length=250, null=True)),
                ('error_column', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Spectrum Job Contact',
                'verbose_name_plural': 'Spectrum Job Contacts',
                'db_table': 'spectrum_job_contact',
                'indexes': [models.Index(fields=['company_code', 'job_number'], name='spectrum_jo_company_ce249a_idx'), models.Index(fields=['contact_id'], name='spectrum_jo_contact_2bc9ba_idx'), models.Index(fields=['last_name'], name='spectrum_jo_last_na_45f761_idx')],
                'unique_together': {('company_code', 'job_number', 'contact_id')},
            },
        ),
    ]
