# Generated by Django 4.2.7 on 2026-01-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum', '0005_alter_spectrumjob_address_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumJobUDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(help_text='Valid Spectrum Company', max_length=3)),
                ('job_number', models.CharField(help_text='Job File Maintenance', max_length=10)),
                ('udf1', models.CharField(blank=True, help_text='User Defined Field 1', max_length=20, null=True)),
                ('udf2', models.CharField(blank=True, help_text='User Defined Field 2', max_length=20, null=True)),
                ('udf3', models.CharField(blank=True, help_text='User Defined Field 3', max_length=20, null=True)),
                ('udf4', models.CharField(blank=True, help_text='User Defined Field 4', max_length=20, null=True)),
                ('udf5', models.CharField(blank=True, help_text='User Defined Field 5', max_length=20, null=True)),
                ('udf6', models.CharField(blank=True, help_text='User Defined Field 6', max_length=20, null=True)),
                ('udf7', models.CharField(blank=True, help_text='User Defined Field 7', max_length=20, null=True)),
                ('udf8', models.CharField(blank=True, help_text='User Defined Field 8', max_length=20, null=True)),
                ('udf9', models.CharField(blank=True, help_text='User Defined Field 9', max_length=20, null=True)),
                ('udf10', models.CharField(blank=True, help_text='User Defined Field 10', max_length=20, null=True)),
                ('udf11', models.CharField(blank=True, help_text='User Defined Field 11', max_length=20, null=True)),
                ('udf12', models.CharField(blank=True, help_text='User Defined Field 12', max_length=20, null=True)),
                ('udf13', models.CharField(blank=True, help_text='User Defined Field 13', max_length=20, null=True)),
                ('udf14', models.CharField(blank=True, help_text='User Defined Field 14', max_length=20, null=True)),
                ('udf15', models.CharField(blank=True, help_text='User Defined Field 15', max_length=20, null=True)),
                ('udf16', models.CharField(blank=True, help_text='User Defined Field 16', max_length=20, null=True)),
                ('udf17', models.CharField(blank=True, help_text='User Defined Field 17', max_length=20, null=True)),
                ('udf18', models.CharField(blank=True, help_text='User Defined Field 18', max_length=20, null=True)),
                ('udf19', models.CharField(blank=True, help_text='User Defined Field 19', max_length=20, null=True)),
                ('udf20', models.CharField(blank=True, help_text='User Defined Field 20', max_length=20, null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error Code if any', max_length=1, null=True)),
                ('error_description', models.CharField(blank=True, help_text='Error Description if any', max_length=250, null=True)),
                ('error_column', models.CharField(blank=True, help_text='Error Column if any', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time this UDF was synced from Spectrum', null=True)),
            ],
            options={
                'verbose_name': 'Spectrum Job UDF',
                'verbose_name_plural': 'Spectrum Job UDFs',
                'db_table': 'spectrum_job_udf',
                'indexes': [models.Index(fields=['company_code', 'job_number'], name='spectrum_jo_company_ab8135_idx')],
                'unique_together': {('company_code', 'job_number')},
            },
        ),
        migrations.CreateModel(
            name='SpectrumJobCostProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(help_text='Valid Spectrum Company', max_length=3)),
                ('job_number', models.CharField(help_text='Job File Maintenance', max_length=10)),
                ('phase_code', models.CharField(help_text='Phase number (no dashes)', max_length=20)),
                ('cost_type', models.CharField(help_text='Cost type', max_length=3)),
                ('transaction_date', models.DateField(help_text='Transaction Date (MM/DD/CCYY)')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Projected Dollars At Completion (allows negative)', max_digits=14, null=True)),
                ('projected_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Projected Hours At Completion (allows negative)', max_digits=14, null=True)),
                ('projected_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Projected Quantity At Completion (allows negative)', max_digits=14, null=True)),
                ('note', models.CharField(blank=True, help_text='Memo', max_length=80, null=True)),
                ('operator', models.CharField(blank=True, help_text='Operator code', max_length=3, null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error Code if any', max_length=1, null=True)),
                ('error_description', models.CharField(blank=True, help_text='Error Description if any', max_length=250, null=True)),
                ('error_column', models.CharField(blank=True, help_text='Error Column if any', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time this projection was synced to Spectrum', null=True)),
            ],
            options={
                'verbose_name': 'Spectrum Job Cost Projection',
                'verbose_name_plural': 'Spectrum Job Cost Projections',
                'db_table': 'spectrum_job_cost_projection',
                'indexes': [models.Index(fields=['company_code', 'job_number'], name='spectrum_jo_company_45cf3a_idx'), models.Index(fields=['transaction_date'], name='spectrum_jo_transac_44e5e9_idx'), models.Index(fields=['phase_code', 'cost_type'], name='spectrum_jo_phase_c_c21b0f_idx')],
                'unique_together': {('company_code', 'job_number', 'phase_code', 'cost_type', 'transaction_date')},
            },
        ),
    ]
