# Generated by ChatGPT on 2026-01-27
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spectrum", "0006_spectrumjobudf_spectrumjobcostprojection"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpectrumSyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_type", models.CharField(choices=[("MANUAL", "MANUAL"), ("AUTO", "AUTO")], default="AUTO", max_length=10)),
                ("status", models.CharField(choices=[("RUNNING", "RUNNING"), ("SUCCESS", "SUCCESS"), ("FAILED", "FAILED")], default="RUNNING", max_length=10)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("company_code", models.CharField(blank=True, max_length=3, null=True)),
                ("divisions", models.JSONField(blank=True, default=list)),
                ("status_code", models.CharField(blank=True, max_length=5, null=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "spectrum_sync_run",
            },
        ),
        migrations.CreateModel(
            name="SpectrumRawPayload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.CharField(max_length=50)),
                ("request_params", models.JSONField(blank=True, default=dict)),
                ("raw_xml_gzip", models.BinaryField(blank=True, null=True)),
                ("item_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payloads", to="spectrum.spectrumsyncrun")),
            ],
            options={
                "db_table": "spectrum_raw_payload",
            },
        ),
        migrations.AddIndex(
            model_name="spectrumsyncrun",
            index=models.Index(fields=["started_at"], name="spectrum_sy_started_5f8c09_idx"),
        ),
        migrations.AddIndex(
            model_name="spectrumsyncrun",
            index=models.Index(fields=["status"], name="spectrum_sy_status_0f0cdd_idx"),
        ),
        migrations.AddIndex(
            model_name="spectrumsyncrun",
            index=models.Index(fields=["run_type"], name="spectrum_sy_run_typ_7506d1_idx"),
        ),
        migrations.AddIndex(
            model_name="spectrumrawpayload",
            index=models.Index(fields=["endpoint", "created_at"], name="spectrum_ra_endpoin_3a96d4_idx"),
        ),
    ]
