# Generated by Django 5.2.10 on 2026-01-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum', '0007_spectrum_sync_run_and_raw_payload'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='spectrumrawpayload',
            new_name='spectrum_ra_endpoin_0e0c02_idx',
            old_name='spectrum_ra_endpoin_3a96d4_idx',
        ),
        migrations.RenameIndex(
            model_name='spectrumsyncrun',
            new_name='spectrum_sy_started_ba41ac_idx',
            old_name='spectrum_sy_started_5f8c09_idx',
        ),
        migrations.RenameIndex(
            model_name='spectrumsyncrun',
            new_name='spectrum_sy_status_b718b0_idx',
            old_name='spectrum_sy_status_0f0cdd_idx',
        ),
        migrations.RenameIndex(
            model_name='spectrumsyncrun',
            new_name='spectrum_sy_run_typ_0020e9_idx',
            old_name='spectrum_sy_run_typ_7506d1_idx',
        ),
    ]
