# Generated by Django 4.2.7 on 2026-01-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('SAFETY', 'Safety Officer'), ('HR', 'HR Contact'), ('FINANCE', 'Finance Contact'), ('ADMIN', 'Administrative'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this branch')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Branch Contact',
                'verbose_name_plural': 'Branch Contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
