# Generated by Django 4.2.7 on 2026-01-13 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branchcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='spectrum_division_code',
            field=models.CharField(blank=True, help_text="Spectrum division code (e.g., '111', '121') - used to match jobs from Spectrum", max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='Division code (e.g., 111, 121, 131, 135, 145) - matches Spectrum division codes', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
