# Generated by Django 4.2.7 on 2026-01-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_spectrum_division_code_alter_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='portal_password',
            field=models.CharField(blank=True, help_text="Password for accessing this branch's public portal. Leave blank to disable portal access.", max_length=255, null=True),
        ),
    ]
