# Generated by Django 4.2.7 on 2026-01-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum', '0004_spectrumphaseenhanced_spectrumphase_spectrumjobdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrumjob',
            name='address_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spectrumjob',
            name='address_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spectrumjob',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spectrumjob',
            name='job_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
