# Generated by Django 4.2.7 on 2026-01-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overtime hours worked', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='regular_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Regular hours worked', max_digits=5, null=True),
        ),
    ]
