# Generated by Django 4.2.7 on 2026-01-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0002_timeentry_overtime_hours_timeentry_regular_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='role_on_day',
            field=models.CharField(choices=[('LABORER', 'Laborer'), ('MASON', 'Mason'), ('OPERATOR', 'Operator'), ('BRICKLAYER', 'Bricklayer'), ('PLASTER', 'Plaster'), ('FOREMAN', 'Foreman')], default='LABORER', max_length=20),
        ),
    ]
